kind: pipeline
type: docker      
name: clone       

steps:
  - name: dev_action                     
    image: plugins/git                   
    commands:                            
    when:                               
      branch:
      - dev
      - master

trigger:     
  event:
  - push