version: '2'

services:
  drone-server:
    image: drone/drone:1
    container_name: drone-server
    ports:
      - 80:80
    volumes:
      - /var/lib/drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_SERVER_HOST=1d93-150-117-139-238.jp.ngrok.io
      - DRONE_SERVER_PROTO=http
      - DRONE_RPC_SECRET=db242daf100b137d40f7f40f82168b7b
      - DRONE_GITHUB_CLIENT_ID=cf7f9b43574b70407cce
      - DRONE_GITHUB_CLIENT_SECRET=9960d06d9042894f755e99cd6c4c3038c488ee70

  drone-runner:
    image: drone/drone-runner-docker:1
    container_name: drone-runner
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_SECRET=db242daf100b137d40f7f40f82168b7b
      - DRONE_RUNNER_CAPACITY=2